# Generated by Django 4.0.4 on 2022-06-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba3', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='ID_PRODUCTO')),
                ('nom_producto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
