# Generated by Django 4.0.4 on 2022-06-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba3', '0004_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='ID_VENTA')),
                ('total_venta', models.IntegerField(verbose_name='Monto total de venta')),
                ('descuento', models.CharField(max_length=25, verbose_name='Porcentaje de descuento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba3.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba3.usuario')),
            ],
        ),
    ]
