# Generated by Django 4.0.4 on 2022-06-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba3', '0006_venta_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.IntegerField(null=True, verbose_name='Monto total de venta'),
        ),
    ]
